name: frist workflow


on: 
  push:
    branches:
      - main


jobs:
  example-job:
    runs-on: utuntu-latest

    steps:
      - name: print a welcome massage
        run: echo "welcome"


      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: list repostory files
        run: ls-la
